version: "2"

networks:
  newsbot:
    external: false

services:
  app:
    #image: jtom38/newsbot:latest
    image: newsbot:latest
    environment:
      #NEWSBOT_POGO_ENABLED: 'true'
      #NEWSBOT_POGO_HOOK: ""
      #NEWSBOT_PSO2_ENABLED: 'true'
      #NEWSBOT_PSO2_HOOK: ""
    restart: always

    networks:
      - newsbot

    volumes:
      - ~/docker/newsbot/database:/app/mounts/database
