version: "3"

networks:
  newsbot:
    external: false

services:
  app:
    #image: jtom38/newsbot:latest
    image: newsbot:latest
    env_file:
      - ./.env
    environment:
      NEWSBOT_POGO_ENABLED: 'true'
      NEWSBOT_POGO_HOOK: ""
      NEWSBOT_PSO2_ENABLED: 'true'
      NEWSBOT_PSO2_HOOK: ""
    restart: always

    networks:
      - newsbot

    volumes:
      - ~/docker/newsbot/database:/app/mounts/database
